// Simula una llamada a la API que devuelve los catalogos de productos
export const getCatalogProducts = async () => {
  return Promise.resolve({
    "LENTES DE SOL": [
      { name: "LENTE DE SOL PROMO (COLOR)", price: 25.0 },
      { name: "POLO ENNI / ZILO SOL", price: 30.0 },
      { name: "POLO METAL SOL", price: 28.0 },
      { name: "UP SOL", price: 35.0 },
      { name: "RAY BAN", price: 100.0 },
      { name: "ELEVE DEPORTVO VARIOS FRENTES", price: 50.0 },
      { name: "ELEVE SOL PLEGABLE", price: 40.0 },
      { name: "SOL CLIVION", price: 45.0 },
      { name: "SOL PLEGABLE CLIVION FOLDING", price: 60.0 },
      { name: "USUAL POLARIZADO/ USUAL NIÑOS", price: 55.0 },
      { name: "LENTES DE SOL JORDAN POLARIZADOS", price: 80.0 },
      { name: "LENTE DE SOL LAVANETTE", price: 50.0 },
      { name: "LENTES DE SOL ATLANTIS", price: 65.0 },
      { name: "SATURDAY SOL", price: 70.0 },
      { name: "SOL DEPORTIVO SEBAS/ TERRA", price: 90.0 },
    ],
    "FORNITURAS y SERVICIOS": [
      { name: "CORDONES ELASTICADOS ADULTOS / NIÑOS / CUERITOS", price: 5.0 },
      { name: "CORDONES COMUNES", price: 3.0 },
      { name: "CORDONES ELASTICO CON CHUPETE", price: 6.0 },
      { name: "PLAQUETAS", price: 7.0 },
      { name: "PLAQUETAS AUTOHADESIVAS", price: 8.0 },
      { name: "PATILLAS RAYBAN", price: 15.0 },
      { name: "TORNILLOS/ARREGLOS", price: 10.0 },
      { name: "TORNILLO PARTIDO", price: 12.0 },
      { name: "BANDA ELASTICA O SUJETADOR FLEX GUM", price: 4.0 },
      { name: "REPARACION FLEX", price: 25.0 },
      { name: "PASE DE CRISTALES", price: 20.0 },
      { name: "QUITAR AR", price: 3.0 },
      { name: "TORNILLO CON TUERCA", price: 6.0 },
      { name: "CADENITAS GRUESAS", price: 18.0 },
      { name: "CADENITAS", price: 10.0 },
      { name: "CADENITAS CANUTILLOS", price: 12.0 },
      { name: "CUERDITAS SILICON CON PIEDRAS", price: 8.0 },
      { name: "CUERDITAS SILICON", price: 5.0 },
      { name: "COLLAR COLGANTE", price: 7.0 },
      { name: "PAÑITO MICROFIBRA", price: 2.0 },
      { name: "ESTUCHE DE OPTICA ZOLAPA", price: 15.0 },
      { name: "ESTUCHE DE OPTICA CAJITA", price: 12.0 },
      { name: "ESTUCHE PRIMIUM / CARTERITA / ESTUCHE CIERRE SOL", price: 18.0 },
      { name: "ESTUCHE LENTES DE CONTACTO ROSCA / COLOR", price: 10.0 },
      { name: "OREJITAS / tope de silicona", price: 4.0 },
      { name: "CORDON LYCRA ENVOLVENTE / TUBO ALGODON", price: 5.0 },
      { name: "TUBO LYCRA", price: 3.0 },
      { name: "TANZA Y REPARACION", price: 8.0 },
    ],
    LIQUIDOS: [
      { name: "ARLYT EXPRESS 240 ML", price: 6.0 },
      { name: "ARLYT EXPRESS 120ML", price: 4.0 },
      { name: "ARLYT PREMIUM", price: 10.0 },
      { name: "ARLYT LUBRICANTE", price: 7.0 },
      { name: "ARLYT EXPRESS 500ML", price: 12.0 },
      { name: "ARLYT FRESH", price: 5.0 },
      { name: "LIMPIA CRISTALES DE LA OPTICA", price: 3.0 },
      { name: "LIMPIA CRISTALES DE LA OPTICA GRANDE", price: 5.0 },
      { name: "ARTELAC", price: 15.0 },
      { name: "RENU ADVENCE", price: 18.0 },
    ],
    "LENTE DE CONTACTO": [
      {
        name: "LENTES DE CONTACTO ACUVUVE MOIST DIARIO 30 LENTES",
        price: 50.0,
      },
      {
        name: "LENTES DE CONTACTO ACUVUVE OASIS/ACUVE 2 2 SEMANAS",
        price: 45.0,
      },
      { name: "LENTES DE CONTACTO ACUVUVE VITA 1 MES", price: 55.0 },
      { name: "LENTES DE CONTACTO ACUVUVE VITA TORICO", price: 60.0 },
      { name: "BIOFINITY", price: 65.0 },
      { name: "BIOFINITY RANGO ESTENDIDO ESFERICO", price: 70.0 },
      { name: "BIONIFITY TORICO", price: 75.0 },
      { name: "BIOFINITY TORIC RANGO ESTENDIDO", price: 80.0 },
      { name: "AIR OPTIX", price: 50.0 },
      { name: "AIR OPTIX TORIC", price: 55.0 },
      { name: "AVAIRA", price: 45.0 },
      { name: "AVAIRA TORIC", price: 50.0 },
      { name: "SOFLENS 59", price: 40.0 },
      { name: "SOFLENS TORIC 66", price: 45.0 },
      { name: "ULTRA (HIDROGEL)", price: 60.0 },
      { name: "ULTRA TORICO", price: 65.0 },
      { name: "BIOMEDIC", price: 55.0 },
      { name: "BIOMEDIC TORIC", price: 60.0 },
      { name: "AIR OPTIX COLOR", price: 70.0 },
      { name: "BELNDS NEUTRO/ COLOR Y GRADUACION / AIR OPTIX", price: 75.0 },
    ],
  });
};
